# Generated by Django 5.2.7 on 2025-11-20 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_sender_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_convers_d0740f_idx',
        ),
    ]
