# Generated by Django 5.2.7 on 2025-11-23 15:40

import chat.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_attachment_type_message_attachment_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='attachment_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='attachment_url',
        ),
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=chat.storage.MixedMediaCloudinaryStorage(), upload_to='chat_attachments/'),
        ),
    ]
