# Generated by Django 5.2.7 on 2025-10-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_verified_user_otp_code_user_otp_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doctor_type',
            field=models.CharField(blank=True, help_text='Loại bác sĩ (official, student, intern)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='license_number',
            field=models.CharField(blank=True, help_text='Số chứng chỉ hành nghề', max_length=100, null=True),
        ),
    ]
