# Generated by Django 5.2.7 on 2025-10-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_doctor_type_alter_user_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='doctor_type',
            field=models.CharField(blank=True, choices=[('doctor', 'Bác sĩ chính thức'), ('student', 'Sinh viên y khoa'), ('intern', 'Thực tập sinh')], max_length=50, null=True),
        ),
    ]
