# Generated by Django 5.2.7 on 2025-11-23 08:51

import django.core.validators
import social.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_postmedia_created_at_alter_postmedia_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='file',
            field=models.FileField(storage=social.models.MixedMediaCloudinaryStorage(), upload_to='posts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'webm'])]),
        ),
    ]
